// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.19.1
// source: serviceapis.proto

package grpcprotobufplay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddressBook *AddressBook `protobuf:"bytes,1,opt,name=addressBook,proto3" json:"addressBook,omitempty"`
}

func (x *AddressBookRequest) Reset() {
	*x = AddressBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceapis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBookRequest) ProtoMessage() {}

func (x *AddressBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceapis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBookRequest.ProtoReflect.Descriptor instead.
func (*AddressBookRequest) Descriptor() ([]byte, []int) {
	return file_serviceapis_proto_rawDescGZIP(), []int{0}
}

func (x *AddressBookRequest) GetAddressBook() *AddressBook {
	if x != nil {
		return x.AddressBook
	}
	return nil
}

type AddressBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *AddressBookResponse) Reset() {
	*x = AddressBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serviceapis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBookResponse) ProtoMessage() {}

func (x *AddressBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceapis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBookResponse.ProtoReflect.Descriptor instead.
func (*AddressBookResponse) Descriptor() ([]byte, []int) {
	return file_serviceapis_proto_rawDescGZIP(), []int{1}
}

func (x *AddressBookResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_serviceapis_proto protoreflect.FileDescriptor

var file_serviceapis_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x62, 0x6f, 0x6f, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0b,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x52,
	0x0b, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x22, 0x31, 0x0a, 0x13,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x49, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x41, 0x70,
	0x69, 0x12, 0x37, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x13, 0x2e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x68, 0x75, 0x6c, 0x68, 0x65,
	0x67, 0x64, 0x65, 0x2f, 0x67, 0x6f, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x67, 0x6f, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x70,
	0x6c, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serviceapis_proto_rawDescOnce sync.Once
	file_serviceapis_proto_rawDescData = file_serviceapis_proto_rawDesc
)

func file_serviceapis_proto_rawDescGZIP() []byte {
	file_serviceapis_proto_rawDescOnce.Do(func() {
		file_serviceapis_proto_rawDescData = protoimpl.X.CompressGZIP(file_serviceapis_proto_rawDescData)
	})
	return file_serviceapis_proto_rawDescData
}

var file_serviceapis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_serviceapis_proto_goTypes = []interface{}{
	(*AddressBookRequest)(nil),  // 0: AddressBookRequest
	(*AddressBookResponse)(nil), // 1: AddressBookResponse
	(*AddressBook)(nil),         // 2: AddressBook
}
var file_serviceapis_proto_depIdxs = []int32{
	2, // 0: AddressBookRequest.addressBook:type_name -> AddressBook
	0, // 1: AddressBookApi.SayHello:input_type -> AddressBookRequest
	1, // 2: AddressBookApi.SayHello:output_type -> AddressBookResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_serviceapis_proto_init() }
func file_serviceapis_proto_init() {
	if File_serviceapis_proto != nil {
		return
	}
	file_addressbook_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_serviceapis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serviceapis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serviceapis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serviceapis_proto_goTypes,
		DependencyIndexes: file_serviceapis_proto_depIdxs,
		MessageInfos:      file_serviceapis_proto_msgTypes,
	}.Build()
	File_serviceapis_proto = out.File
	file_serviceapis_proto_rawDesc = nil
	file_serviceapis_proto_goTypes = nil
	file_serviceapis_proto_depIdxs = nil
}
