// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.19.1
// source: serviceapis.proto

package grpcprotobufplay

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AddressBookApiClient is the client API for AddressBookApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddressBookApiClient interface {
	SayHello(ctx context.Context, in *AddressBookRequest, opts ...grpc.CallOption) (*AddressBookResponse, error)
}

type addressBookApiClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressBookApiClient(cc grpc.ClientConnInterface) AddressBookApiClient {
	return &addressBookApiClient{cc}
}

func (c *addressBookApiClient) SayHello(ctx context.Context, in *AddressBookRequest, opts ...grpc.CallOption) (*AddressBookResponse, error) {
	out := new(AddressBookResponse)
	err := c.cc.Invoke(ctx, "/AddressBookApi/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressBookApiServer is the server API for AddressBookApi service.
// All implementations must embed UnimplementedAddressBookApiServer
// for forward compatibility
type AddressBookApiServer interface {
	SayHello(context.Context, *AddressBookRequest) (*AddressBookResponse, error)
	mustEmbedUnimplementedAddressBookApiServer()
}

// UnimplementedAddressBookApiServer must be embedded to have forward compatible implementations.
type UnimplementedAddressBookApiServer struct {
}

func (UnimplementedAddressBookApiServer) SayHello(context.Context, *AddressBookRequest) (*AddressBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedAddressBookApiServer) mustEmbedUnimplementedAddressBookApiServer() {}

// UnsafeAddressBookApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddressBookApiServer will
// result in compilation errors.
type UnsafeAddressBookApiServer interface {
	mustEmbedUnimplementedAddressBookApiServer()
}

func RegisterAddressBookApiServer(s grpc.ServiceRegistrar, srv AddressBookApiServer) {
	s.RegisterService(&AddressBookApi_ServiceDesc, srv)
}

func _AddressBookApi_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressBookApiServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AddressBookApi/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressBookApiServer).SayHello(ctx, req.(*AddressBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AddressBookApi_ServiceDesc is the grpc.ServiceDesc for AddressBookApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddressBookApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AddressBookApi",
	HandlerType: (*AddressBookApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _AddressBookApi_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviceapis.proto",
}
