// Code generated by protoc-gen-go. DO NOT EDIT.
// source: address.proto

package main

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person_PhoneType int32

const (
	Person_CELL Person_PhoneType = 0
	Person_HOME Person_PhoneType = 1
	Person_WORK Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "CELL",
	1: "HOME",
	2: "WORK",
}

var Person_PhoneType_value = map[string]int32{
	"CELL": 0,
	"HOME": 1,
	"WORK": 2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}

func (Person_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{0, 0}
}

type Person struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string                `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones               []*Person_PhoneNumber `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*Person_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_PhoneNumber struct {
	Number               string           `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Person_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=main.Person_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Person_PhoneNumber) Reset()         { *m = Person_PhoneNumber{} }
func (m *Person_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person_PhoneNumber) ProtoMessage()    {}
func (*Person_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{0, 0}
}

func (m *Person_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person_PhoneNumber.Unmarshal(m, b)
}
func (m *Person_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Person_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person_PhoneNumber.Merge(m, src)
}
func (m *Person_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Person_PhoneNumber.Size(m)
}
func (m *Person_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Person_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Person_PhoneNumber proto.InternalMessageInfo

func (m *Person_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_PhoneNumber) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_CELL
}

// out address book
type AddressBook struct {
	Person               []*Person `protobuf:"bytes,1,rep,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddressBook) Reset()         { *m = AddressBook{} }
func (m *AddressBook) String() string { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()    {}
func (*AddressBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{1}
}

func (m *AddressBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBook.Unmarshal(m, b)
}
func (m *AddressBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBook.Marshal(b, m, deterministic)
}
func (m *AddressBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBook.Merge(m, src)
}
func (m *AddressBook) XXX_Size() int {
	return xxx_messageInfo_AddressBook.Size(m)
}
func (m *AddressBook) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBook.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBook proto.InternalMessageInfo

func (m *AddressBook) GetPerson() []*Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func init() {
	proto.RegisterEnum("main.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
	proto.RegisterType((*Person)(nil), "main.Person")
	proto.RegisterType((*Person_PhoneNumber)(nil), "main.Person.PhoneNumber")
	proto.RegisterType((*AddressBook)(nil), "main.AddressBook")
}

func init() { proto.RegisterFile("address.proto", fileDescriptor_982c640dad8fe78e) }

var fileDescriptor_982c640dad8fe78e = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0x74, 0xbb, 0xd8, 0x89, 0x96, 0x30, 0x48, 0x59, 0x3c, 0x85, 0xe0, 0x21, 0x7a,
	0x08, 0xd2, 0x3e, 0x81, 0x4a, 0x41, 0xb0, 0xda, 0xba, 0x08, 0x9e, 0x53, 0x32, 0x60, 0xd0, 0xec,
	0x2e, 0x49, 0x3d, 0xf4, 0xb5, 0x7d, 0x02, 0xc9, 0x64, 0x91, 0x80, 0xb7, 0x6f, 0x66, 0x7e, 0xbe,
	0x19, 0x06, 0xce, 0xcb, 0xaa, 0x6a, 0xa9, 0xeb, 0x0a, 0xdf, 0xba, 0x83, 0x43, 0xd9, 0x94, 0xb5,
	0xcd, 0x7e, 0x04, 0xa8, 0x1d, 0xb5, 0x9d, 0xb3, 0x88, 0x20, 0x6d, 0xd9, 0x90, 0x16, 0xa9, 0xc8,
	0x67, 0x86, 0x19, 0xe7, 0x10, 0xd5, 0x95, 0x8e, 0x52, 0x91, 0x4f, 0x4d, 0x54, 0x57, 0x78, 0x01,
	0x53, 0x6a, 0xca, 0xfa, 0x4b, 0x4f, 0x38, 0x34, 0x14, 0x78, 0x0b, 0xca, 0x7f, 0x38, 0x4b, 0x9d,
	0x96, 0xe9, 0x24, 0x8f, 0x97, 0xba, 0xe8, 0xdd, 0xc5, 0xe0, 0x2d, 0x76, 0xfd, 0xe8, 0xe5, 0xbb,
	0xd9, 0x53, 0x6b, 0x42, 0xee, 0xf2, 0x15, 0xe2, 0x51, 0x1b, 0x17, 0xa0, 0x2c, 0x53, 0x58, 0x1e,
	0x2a, 0xbc, 0x01, 0x79, 0x38, 0x7a, 0xe2, 0x03, 0xe6, 0xcb, 0xc5, 0x7f, 0xed, 0xdb, 0xd1, 0x93,
	0xe1, 0x4c, 0x76, 0x0d, 0xb3, 0xbf, 0x16, 0x9e, 0x82, 0x7c, 0x58, 0x6f, 0x36, 0xc9, 0x49, 0x4f,
	0x8f, 0xdb, 0xe7, 0x75, 0x22, 0x7a, 0x7a, 0xdf, 0x9a, 0xa7, 0x24, 0xca, 0x56, 0x10, 0xdf, 0x0d,
	0xbf, 0xb8, 0x77, 0xee, 0x13, 0xaf, 0x40, 0x79, 0x76, 0x6a, 0xc1, 0xe7, 0x9f, 0x8d, 0xf7, 0x98,
	0x30, 0xdb, 0x2b, 0x7e, 0xdb, 0xea, 0x37, 0x00, 0x00, 0xff, 0xff, 0x58, 0x68, 0x1b, 0xef, 0x47,
	0x01, 0x00, 0x00,
}
